# -*- coding: utf-8 -*-
"""Final Project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bR0W1aPAO2bNsMNJ2_Fxo0779fYsWno3
"""

# getting data from google drive
from google.colab import drive

drive.mount('/content/gdrive')

import glob
import matplotlib.pyplot as plt
from IPython.display import display, Image

import cv2
import numpy as np

# Load images in greyscale.
degas_paths = list(glob.glob('gdrive/My Drive/MAIS Final Project Data/Degas/*.jpg'))
durer_paths = list(glob.glob('gdrive/My Drive/MAIS Final Project Data/Durer/*.jpg'))
gaugin_paths = list(glob.glob('gdrive/My Drive/MAIS Final Project Data/Gaugin/*.jpg'))
goya_paths = list(glob.glob('gdrive/My Drive/MAIS Final Project Data/Goya/*.jpg'))
picasso_paths = list(glob.glob('gdrive/My Drive/MAIS Final Project Data/Picasso/*.jpg'))
rembrant_paths = list(glob.glob('gdrive/My Drive/MAIS Final Project Data/Rembrant/*.jpg'))
renoir_paths = list(glob.glob('gdrive/My Drive/MAIS Final Project Data/Renoir/*.jpg'))
sisely_paths = list(glob.glob('gdrive/My Drive/MAIS Final Project Data/Sisely/*.jpg'))
titian_paths = list(glob.glob('gdrive/My Drive/MAIS Final Project Data/Titian/*.jpg'))
vangogh_paths = list(glob.glob('gdrive/My Drive/MAIS Final Project Data/Van_Gogh/*.jpg'))
# putting all images together
image_paths = degas_paths + durer_paths + gaugin_paths + goya_paths + picasso_paths + rembrant_paths + renoir_paths + sisely_paths + titian_paths + vangogh_paths
print(image_paths)

#resixing images and turning to gray-scale
resized_images = []
for path in image_paths:
  img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
  resized_images.append(cv2.resize(img, (400, 400)))

# putting all images in one matrix
images = np.stack([x for x in resized_images])

#flattening images
num_images = len(images)
images = images.reshape(num_images, -1)

#applying PCA from sci-kit
from sklearn.decomposition import PCA

pca = PCA(n_components=10)
pca.fit(images)

print(pca.explained_variance_ratio_)
